### ISSUE TITLE
Application Request: keybase.app

### ISSUE THREAD

**Issue by lgutter** [nloomans/Codam.app#4]
**Website URL:** https://keybase.io/

thanks! :)

**Comment by nloomans** [comment]
I'll look into this, but it might be difficult to package for the Codam iMacs because Keybase creates a `/keybase` mount point. While it appears to be movable I'm not sure if we even have permission to create a loopback mount point. It also appears to be possible to disable this feature entirely but that would be a last resort.

Some resources for me to look into:

 - https://keybase.io/docs/kbfs
 - https://github.com/keybase/client/issues/4739
 - https://github.com/keybase/keybase-issues/issues/2306

**Comment by EuanHoll** [comment]
We now how the gui added. Unfortunately anything to do with gut repositories won't work as you need root. This is unfortunately the best we'll be able to do.

**Comment by EuanHoll** [comment]
I'm going to close this issue because we've done the best we can do with this program.
